INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (1, 1, 46, '2021-06-13 22:45', 'Explicando el límite al infinito de un conseno');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (2, 1, 97, '2021-06-14 10:52', 'Explicando un ejercicio de números complejos');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (3, 1, 1074, '2021-06-14 12:05', 'Explicando derivaciones de funciones implícitas');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (4, 1, 248, '2021-06-15 12:11', 'Consultas sobre expresiones algebráicas simples, y sobre la regla de la cadena');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (5, 1, 346, '2021-06-15 14:33', 'Domino de una tangente');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (6, 1, 515, '2021-06-15 16:00', 'Aclaración sobre las derivadas laterlaes');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (7, 1, 690, '2021-06-15 16:26', 'Aclaración sobre el análisis de la derivación en una función en ramas dada');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (8, 1, 285, '2021-06-15 19:13', 'Ayuda en el factoreo de una expresión para eliminar una indeterminación de un límite');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (9, 1, 288, '2021-06-15 22:16', 'Primera ayuda en un evaluativo de Cálculo I');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (10, 1, 308, '2021-06-15 22:29', 'Ayuda 2 en un evaluativo de Cálculo I');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (11, 1, 276, '2021-06-15 22:40', 'Ayuda 3 en el evaluativo de Cálculo I: la derivada de orden mayor');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (12, 1, 96, '2021-06-16 15:33', 'Explicación de la ecuación cuadrática factoreada');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (13, 1, 264, '2021-06-18 19:43', 'Explicación sobre trabajo realizado');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (14, 1, 919, '2021-06-21 17:42', 'Dudas varias sobre números complejos');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (15, 1, 65, '2021-06-21 19:45', 'Duda sobre un número complejo');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (16, 1, 815, '2021-06-22 09:57', 'Dudas de ejercicios de complejos');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (17, 1, 603, '2021-06-22 11:34', 'Consultas varias sobre complejos');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (18, 1, 37, '2021-06-22 12:08', 'Duda sobre suma o resta de complejos');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (19, 1, 1219, '2021-06-22 13:00', 'Resolución del punto 25 de números complejos');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (20, 1, 277, '2021-06-22 13:07', 'Revisión de ejercicio 27 de números complejos');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (21, 1, 71, '2021-06-22 13:47', 'Aclaración sobre las vueltas de los distintos números complejos que se despejan');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (22, 1, 188, '2021-06-23 15:34', 'Aclaración sobre el complemento de un complejo expresado en forma exponencial');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (23, 1, 742, '2021-06-23 20:00', 'Ayuda con un examen de Álgebra');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (24, 1, 2400, '2021-06-24 15:13', 'Consultas varias pre-parcial de Álgebra');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (25, 1, 167, '2021-06-26 12:41', 'Duda sobre la regla de L''Hôpital');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (26, 1, 189, '2021-06-27 17:40', 'Duda sobre el dominio de una función, y duda sobre el despeje en una ecuación con una secante');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (27, 1, 31, '2021-06-27 20:21', 'Duda sobre derivadas');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (28, 1, 519, '2021-06-28 10:53', 'Dudas sobre función inversa y monotonía');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (29, 1, 480, '2021-06-28 11:34', 'Discusión sobre la monotonía de sec x - tg x');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (30, 1, 137, '2021-06-28 11:43', 'Derivada del arco seno para comparar');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (31, 1, 138, '2021-06-28 13:08', 'Duda de si se puede aplicar muchas veces consecutivas la regla de L''Hôpital');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (32, 1, 230, '2021-06-28 16:15', 'Un par de confirmaciones. Las dos en relación con la regla de L''Hôpital');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (33, 1, 272, '2021-06-29 16:10', 'Resolución de dudas sobre asíntotas');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (34, 1, 533, '2021-06-29 18:41', 'Un par de dudas sobre derivadas de segundo orden');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (35, 1, 197, '2021-06-29 18:58', 'Revisión de una derivada de segundo orden');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (36, 1, 180, '2021-06-29 19:22', 'Cálculo de la velocidad de un dron a los 6 segundos');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (37, 1, 463, '2021-06-29 19:32', 'Búsqueda de un error en un ejercicio de derivadas');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (38, 1, 67, '2021-06-29 22:16', 'Duda sobre signos');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (39, 1, 1039, '2021-06-30 11:58', 'Consulta pre-parcial Cálculo I');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (40, 1, 533, '2021-07-07 19:04', 'Revisión de 2do parcial de Cálculo I');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (41, 1, 473, '2021-07-14 13:30', 'Duda sobre MCUV');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (42, 1, 117, '2021-08-24 19:00', 'Duda sobre comprobación de primitivas en Cálculo II');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (43, 1, 48, '2021-08-25 13:17', 'Pregunta sobre unas proyecciones de un cuerpo');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (44, 1, 102, '2021-08-25 13:24', 'Duda sobre las proporciones entre distintos cuerpos');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (45, 1, 120, '2021-08-25 13:39', 'Revisión de las proyecciones de un cuerpo 1-2-4');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (46, 1, 258, '2021-08-25 19:03', 'Corrección de proyección del Cuerpo 4');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (47, 1, 53, '2021-08-26 15:52', 'Pregunta sobre si van líneas de trazos en una vista lateral');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (48, 1, 50, '2021-08-31 12:36', 'Revisión de prespectivas de cuerpo poliédrico simple');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (49, 1, 45, '2021-08-31 16:58', 'Aclaración sobre las líneas auxiliares');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (50, 1, 32, '2021-08-31 17:28', 'Revisando otras perspectivas');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (51, 1, 32, '2021-08-31 20:21', 'Revisión de la lámina de caligrafía');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (52, 1, 341, '2021-09-01 18:34', 'Resultados de integrales basados en las áreas bajo las gráficas');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (53, 1, 442, '2021-09-02 20:00', 'Ayuda en la conversión a base 10 de un número en base X');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (54, 1, 720, '2021-09-07 12:57', 'Ayuda en la interpretación de un cuerpo poliédrico');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (55, 1, 17, '2021-09-07 15:35', 'Pregunta de si sé dibujar las proyecciones de una cara, y perspectiva en la otra');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (56, 1, 90, '2021-09-08 10:38', 'Duda sobre derivadas');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (57, 1, 157, '2021-09-08 19:00', 'Duda sobre matrices elementales');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (58, 1, 720, '2021-09-09 10:18', 'Duda sobre matrices equivalentes y rango de una matriz');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (59, 1, 343, '2021-09-09 12:18', 'Cómo limitar el rango de una matriz');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (60, 1, 120, '2021-09-10 19:16', 'Revisión de interpretación de cuerpo incorrecto');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (61, 1, 49, '2021-09-10 20:44', 'Revisión del cuerpo con proyecciones y perspectiva resueltos');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (62, 1, 1655, '2021-09-12 23:10', 'Ayuda en un evaluativo de Cálculo II');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (63, 1, 600, '2021-09-13 18:42', 'Dudas varias de Cálculo II');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (64, 1, 742, '2021-09-14 16:40', 'Interpretación de figura difícil');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (65, 1, 4100, '2021-09-27 10:48', 'Relleno');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (66, 1, 250, '2021-09-27 14:50', 'Explicación sobre determinantes');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (67, 1, 167, '2021-09-28 12:34', 'Explicando cómo sacar la recta tangente a un punto en una curva');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (68, 1, 229, '2021-09-28 13:22', 'Ayuda con el cálculo de intervalos');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (69, 1, 420, '2021-09-28 16:13', 'Ejercicio de arco de longitud de curva');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (70, 1, 30, '2021-09-29 10:15', 'Explicando inversión de límites de integración para uso del Teorema Fundamental del Cálculo');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (71, 1, 1094, '2021-09-30 23:10', 'Ayuda en el seccionamiento de un cuerpo de forma cúbica');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (72, 1, 240, '2021-09-30 23:25', 'Ayuda en las proyecciones del cuerpo cúbico seccionado');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (73, 1, 83, '2021-10-02 16:33', 'Duda sobre el dominio de un logaritmo');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (74, 1, 816, '2021-10-02 17:50', 'Dudas sobre límites e integrales con logaritmos');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (75, 1, 141, '2021-10-02 18:04', 'Explicación del no reemplazo de límites en la integral por partes');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (76, 1, 98, '2021-10-03 18:37', '¿Por qué no es una exponencial una variable elevada a una constante?');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (77, 1, 131, '2021-10-03 20:44', 'Aclaración de la Regla de L''Hôpital');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (78, 1, 600, '2021-10-06 12:26', 'Dudas sobre Elementos de Álgebra Lineal antes del parcial');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (79, 1, 120, '2021-10-07 13:12', 'Pregunta sobre un parcial');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (80, 1, 480, '2021-10-07 19:50', 'Revisión de parcial de Sistemas de Representación');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (81, 1, 792, '2021-10-15 16:45', 'Ayuda sobre geometría descriptiva');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (82, 1, 102, '2021-10-15 21:35', 'Revisión ejercicio 1 de cambio de planos');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (83, 1, 113, '2021-10-16 14:09', 'Revisión de segundo ejercicio de cambios de planos');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (84, 1, 93, '2021-10-19 11:16', 'Pregunta sobre el if-else en los algoritmos');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (85, 1, 132, '2021-10-19 21:38', 'Pregunta sobre la caligrafía normalizada en un plano pequeño');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (86, 1, 642, '2021-10-22 11:53', 'Ayuda con algoritmos para el parcial de Informática');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (87, 1, 395, '2021-10-22 20:46', 'Ayuda sobre el dibujo de una perspectiva de un cuerpo con ejes');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (88, 1, 2400, '2021-11-01 17:27', 'Un par de integrales. Una que se resuelve sustituyendo el senh y otra por sustitución trigonométrica');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (89, 1, 157, '2021-11-01 17:42', 'Explicando el método de sustitución trigonométrica');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (90, 1, 420, '2021-11-02 14:21', 'Ayuda con subprogramas');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (91, 1, 132, '2021-11-02 16:13', 'Ayuda en interpretación de una consigna para un algoritmo');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (92, 1, 152, '2021-11-03 22:37', 'Corrección de la perspectiva de un cuerpo con 3 ejes');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (93, 1, 87, '2021-11-06 14:14', 'Enseñando lo que son los planos auxiliares para las proyecciones de cuerpos de revolución');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (94, 1, 1714, '2021-11-07 17:18', 'Ayuda en evaluativo sobre Espacios Vectoriales');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (95, 1, 375, '2021-11-07 18:38', 'Revisión de integración por sustitución trigonométrica');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (96, 1, 314, '2021-11-07 18:50', 'Revisión de resolución completa de la integral con sustitución trigonométrica');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (97, 1, 409, '2021-11-07 19:33', 'Control de ejercicio con integración por sustitución trigonométrica');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (98, 1, 124, '2021-11-07 19:51', 'Ayuda en otra integral con sustitución trigonométrica');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (99, 1, 339, '2021-11-08 12:57', 'Corrección de un 1/cotg(x) mal reacomodado');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (100, 1, 67, '2021-11-08 15:16', 'Consejo: usar sustitución simple en un sen(x)/cos(x)');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (101, 1, 1108, '2021-11-10 22:58', 'Explicando los parámetros de la función main()');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (102, 1, 66, '2021-11-11 21:34', '¿Cuándo usar planos auxiliares?');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (103, 1, 353, '2021-11-12 14:56', 'Aclaración de lo que hay que hacer en el práctico de piezas de máquinas');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (104, 1, 208, '2021-11-12 18:25', 'Un par de dudas más sobre los cortes');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (105, 1, 300, '2021-11-12 19:28', 'Dudas sobre las líneas de los cortes');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (106, 1, 300, '2021-11-23 13:13', 'Explicación del teorema de los ejes paralelos');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (107, 1, 1578, '2021-11-28 12:34', 'Ayuda en evaluativo sobre Valores y Vectores Propios');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (108, 1, 63, '2021-12-01 18:32', 'Explicación de las derivadas parciales en una función de una onda mecánica');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (109, 1, 613, '2021-12-05 11:43', 'Un par de ejercicios de complejos en los que hay que graficar según el módulo de Z');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (110, 1, 59, '2021-12-15 10:35', 'Control de un pequeño ejercicio de Álgebra y Geometría Analítica');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (111, 1, 224, '2021-12-16 19:21', 'Demostración de vectores perpendiculares');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (112, 1, 120, '2022-01-28 12:10', 'Resolución de una integral que se resuelve con sustitución trigonométrica');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (113, 1, 600, '2022-01-31 19:03', 'Explicando una integral impropia de una función trigonométrica');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (114, 1, 97, '2022-01-31 19:09', 'Factorización de un número dentro de una raíz');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (115, 1, 53, '2022-02-01 17:48', 'Esboce de gráfica');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (116, 1, 18, '2022-02-03 17:08', 'Forma de la ecuación cuadrática factoreada');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (117, 1, 120, '2022-02-03 19:17', 'Integral de 1/(x^2+4)');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (118, 1, 112, '2022-02-04 20:34', 'Ceros de una ecuación cuadrática');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (119, 1, 193, '2022-02-07 18:47', 'Explicando por qué un numerador de un límite infinito da infinito');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (120, 1, 280, '2022-02-09 18:21', 'Dudas sobre series');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (121, 1, 294, '2022-02-10 12:06', 'Duda sobre usos de criterios de comparación en series infinitas');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (122, 1, 270, '2022-02-10 15:43', 'Serie de una función trigonométrica');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (123, 1, 207, '2022-02-10 20:47', 'Integral con sustitución trigonométrica');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (124, 1, 480, '2022-02-11 18:44', 'Ayudas con integrales varias');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (125, 1, 182, '2022-02-12 13:15', 'Sugerencia y corrección en una integral impropia');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (126, 1, 87, '2022-02-28 19:30', 'Explicación de las operaciones internas del argumento del límite');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (127, 1, 88, '2022-03-01 11:09', 'Relleno');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (128, 1, 76, '2022-03-01 12:34', 'Demostración de derivada de constatnte por función');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (129, 1, 396, '2022-03-04 12:32', 'Duda sobre un extremo absoluto');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (130, 1, 300, '2022-03-17 11:36', 'Aclaración de punto aislado');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (131, 1, 186, '2022-03-19 00:41', 'Explicando la identificación y graficación de funciones de dos variables');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (132, 1, 210, '2022-04-06 18:03', 'Explicando cosas sobre una función vectorial');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (133, 1, 438, '2022-04-06 18:23', 'Revisión de ejercicios de derivada direccional');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (134, 1, 1006, '2022-04-07 21:18', 'Resolviendo un ejercicio de Circuitos Eléctricos I');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (135, 1, 540, '2022-04-08 00:05', 'Otro circuito para revisar');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (136, 1, 120, '2022-04-11 11:52', 'Revisión de ejercicio sobre diferenciabilidad');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (137, 1, 279, '2022-04-11 19:14', 'Dudas de ejercicios de derivada direccional de Cálculo III');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (138, 1, 90, '2022-04-13 13:47', 'Explicando cómo la identidad trigonométrica modificó una expresión');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (139, 1, 300, '2022-04-13 15:42', 'Explicación de gradiente');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (140, 1, 387, '2022-04-13 16:01', 'Explicación de diferencia entre derivada y diferencial');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (141, 1, 1800, '2022-04-13 19:27', 'Explicación de conceptos varios de Cálculo III');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (142, 1, 104, '2022-04-19 20:51', 'Ayuda con la resolución de un sistema de ecuaciones de un circuito');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (143, 1, 300, '2022-04-19 21:41', 'Revisión de código');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (144, 1, 480, '2022-04-20 17:53', 'Ejercicio de derivada parcial implícita');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (145, 1, 27, '2022-04-20 18:21', 'Resolución de ejercicio de derivada implícita en donde se debe encontrar la derivada direccional máxima');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (146, 1, 135, '2022-04-30 18:18', 'Duda en cálculo de campos eléctricos con cargas puntuales');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (147, 1, 287, '2022-05-01 20:39', 'Explicación de cálculo de campo magnético en un conductor');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (148, 1, 687, '2022-05-02 23:36', 'Consultas varias de Cálculo III relacionadas a la graficación');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (149, 1, 600, '2022-05-06 00:48', 'Resolución de problemas de posiciones relativas de superficies y curvas');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (150, 1, 1200, '2022-05-09 22:48', 'Preguntas de resolución de Circuitos Eléctricos I');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (151, 1, 438, '2022-05-15 19:10', 'Control de código en C sobre el paso de un arreglo a una función');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (152, 1, 713, '2022-05-19 11:22', 'Revisión de código en C en el que tenía un bucle infinito en un switch');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (153, 1, 854, '2022-05-25 18:18', 'Dudas sobre punteros y variables a la hora de ingresarlos y mandarlos a una función');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (154, 1, 354, '2022-05-25 23:32', 'Cómo copiar el contenido de un vector en otro vector');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (155, 1, 844, '2022-05-26 11:01', 'Explicación del segundo parámetro de entrada del main y su uso');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (156, 1, 242, '2022-06-02 16:50', 'Explicando la graficación de intersección de regiones');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (157, 1, 630, '2022-06-03 20:40', 'Despeje de una tensión de Thévenin mediante método de mallas en la cual una de ellas no tiene corriente');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (158, 1, 60, '2022-06-07 20:36', 'Aclarando el formato de la función fgetc()');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (159, 1, 360, '2022-06-08 20:16', 'Límites con un paraboloide');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (160, 1, 300, '2022-06-12 19:07', 'Explicación del modificador \ en las cadenas de caracteres');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (161, 1, 143, '2022-06-14 00:12', 'Ayuda en interpretación de conjuntos en R3');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (162, 1, 454, '2022-06-14 00:30', 'Uso de la función strtok()');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (163, 1, 206, '2022-06-29 13:17', 'Duda sobre la cambio de recorrido de integración');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (164, 1, 600, '2022-07-02 17:32', 'Error de números en la resolución de un circuito');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (165, 1, 3120, '2022-07-08 20:27', 'Planeación del plan estratégico para la cursada que queda');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (166, 1, 40, '2022-07-22 14:57', 'Ecuación de recta que pasa por dos puntos');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (167, 1, 71, '2022-07-22 14:57', 'Explicación de la indeterminación de un límite');
INSERT INTO Registros (idRegistro, idActividad, segundosConsumidos, fechaCreacion, descripcion) VALUES (168, 1, 780, '2022-08-03 23:52', 'Revisando seccionamiento');
